version: '3'

services:
  tim-test:
    image: tim-test:1.0
    build:
      context: ./
      dockerfile: ./.docker/app.dockerfile
      args:
        buildversion: 1
        PACKAGES: "wget"
    ports:
      - "3000:80"

    # Swarm only
    configs:
      # Config name (preload)
      - source: example
      # Where config will be on container
        target: /app/config/api.cfg
  
    networks:
      - app-net
    volumes:
      - ./logs:/var/www/logs
    environment:
      - NODE_ENV=production
      - APP_VERSION=1.0
      - build=4
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    environment:
      - POSTGRES_PASSWORD_FILE=/secrets/.db.conf

    # Swarm only
    secrets: 
      # Config name (preload)
      - source: encrypted
        # Where config will be on container
        target: /secrets/.db.conf
    
    networks:
      - app-net
  # Adminer, single page utility for DB management https://localhost:8080 to access
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-net
networks:
  app-net:
    driver: bridge

# Swarm only
secrets: 
  encrypted:
    external: true
configs:
  example:
    external: true