version: '1.0'

services:
  tim-test:
    image: timtest:1.0
    build:
      context: ./
      dockerfile: .docker/app.dockerfile
      args:
        buildversion: 1
        PACKAGES: "wget"
    ports:
      - "3000:80"
    networks:
      - app-net
    volumes:
      - ./logs:/var/www/logs
    environment:
      - NODE_ENV=production
      - APP_VERSION=1.0
      - build=4
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - app-net
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-net
networks:
  app-net:
    driver: bridge