version: '1.0'

services:
  tim-test:
    image: timtest:1.0
    build:
      context: ./
      dockerfile: .docker/app.dockerfile
      args:
        buildversion: 1
        PACKAGES: "wget"
    ports:
      - "3000:80"
    networks:
      - app-net
    volumes:
      - ./logs:/var/www/logs
    environment:
      - NODE_ENV=production
      - APP_VERSION=1.0
      - build=4

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    mem_limit: 500m
    # or set shared memory limit when deploy via swarm stack
    environment:
      POSTGRES_PASSWORD: tim

    networks:
      - app-net
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-net
networks:
  app-net:
    driver: bridge